package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.exception.ApiException;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.LoyaltyAccount;
import com.probestack.forgestudio.design.model.UpdateAccountRequest;
import com.probestack.forgestudio.design.repository.UpdateAccountRequestRepository;
import java.lang.Class;
import java.lang.Exception;
import java.lang.Long;
import java.lang.Object;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.System;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.beans.BeanUtils;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for UpdateAccountRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class AccountsService {
    private final UpdateAccountRequestRepository updateAccountRequestRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public AccountsService(UpdateAccountRequestRepository updateAccountRequestRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.updateAccountRequestRepository = updateAccountRequestRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<LoyaltyAccount> getLoyaltyAccount(UUID memberId) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve entity by ID from database
            String repositoryId = toRepositoryId(memberId);
            Optional<UpdateAccountRequest> entity = updateAccountRequestRepository.findById(repositoryId);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getLoyaltyAccount")
                            .resource("UpdateAccountRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("UpdateAccountRequestRepository")
                            .collection("loyalty_rewards_service_accounts")
                            .documentId(repositoryId)
                            .recordCount(entity.isPresent() ? 1 : 0)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            return entity.map(this::mapToLoyaltyAccount).map(ResponseEntity::ok).orElseThrow(() -> ApiException.notFound("UpdateAccountRequest", repositoryId));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getLoyaltyAccount")
                            .resource("UpdateAccountRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("UpdateAccountRequestRepository")
                            .collection("loyalty_rewards_service_accounts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<LoyaltyAccount> updateLoyaltyAccount(UUID memberId,
            UpdateAccountRequest updateAccountRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // Update entity in database
            // Verify entity exists before updating
            String repositoryId = toRepositoryId(memberId);
            if (!updateAccountRequestRepository.existsById(repositoryId)) {
                throw ApiException.notFound("UpdateAccountRequest", repositoryId);
            }
            setEntityId(updateAccountRequest, repositoryId);
            UpdateAccountRequest updatedUpdateAccountRequest = updateAccountRequestRepository.save(updateAccountRequest);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("updateLoyaltyAccount")
                            .resource("UpdateAccountRequest")
                            .action("UPDATE")
                            .status("SUCCESS")
                            .repository("UpdateAccountRequestRepository")
                            .collection("loyalty_rewards_service_accounts")
                            .documentId(getEntityId(updatedUpdateAccountRequest))
                            .recordCount(1)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            LoyaltyAccount response = mapToLoyaltyAccount(updatedUpdateAccountRequest);
            return ResponseEntity.ok(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("updateLoyaltyAccount")
                            .resource("UpdateAccountRequest")
                            .action("UPDATE")
                            .status("FAILED")
                            .repository("UpdateAccountRequestRepository")
                            .collection("loyalty_rewards_service_accounts")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_update_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps UpdateAccountRequest entity to LoyaltyAccount response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private LoyaltyAccount mapToLoyaltyAccount(UpdateAccountRequest entity) {
        // Create new response object
        LoyaltyAccount response = new LoyaltyAccount();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
